name: flutter_event
version: 1.0.0
description: Fire events cross pages and components. Supported both iOS and Android.
homepage: https://github.com/mupiaomiao/flutter_event
repository: https://github.com/mupiaomiao/flutter_event

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.2