name: flutter_event
description: An event package for Flutter.
version: 1.0.0
homepage: https://github.com/mupiaomiao/flutter_event

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter.
flutter: